# Generated by Django 4.1.5 on 2023-01-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id', models.CharField(max_length=5)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('part', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=50)),
                ('programme', models.CharField(max_length=25)),
                ('level', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
