# Generated by Django 4.1.5 on 2023-01-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_member_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
    ]
