# Generated by Django 4.1.5 on 2023-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_remove_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='', upload_to='profile'),
        ),
    ]
