# Generated by Django 4.1.5 on 2023-01-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_member_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
    ]
