# Generated by Django 4.1.4 on 2023-01-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
